---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.0
before_install: gem install bundler -v 2.0.2
install: "bundle install"
script: "bundle exec rake spec"
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby
